export const eventTypes = {
  EVENT_RECEIVE_SUCCESS: "EVENT_RECEIVE_SUCCESS",
  EVENT_FAIL: "EVENT_FAIL",
  EVENT_LOADING: "EVENT_LOADING",
  EVENT_DELETE: "EVENT_DELETE",
  EVENT_DELETE_FAIL: "EVENT_DELETE_FAIL",
};
